[package]
name = "qoo"
version = "0.1.2"
edition = "2018"
authors = ["ochi daiki <lbfdeatq@gmail.com>"]
description = "query builder library. Query Object Oriented."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
